[app]
title = Учёт таксиста
package.name = taxiapp
package.domain = org.taxi
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy
orientation = portrait
fullscreen = 0
android.permissions = INTERNET
android.accept_sdk_license = True
android.archs = arm64-v8a
android.api = 28
android.minapi = 21
android.ndk = 25b
android.gradle_dependencies = 
p4a.branch = master
p4a.bootstrap = sdl2
