[app]
title = Taxi
package.name = taxiapp
package.domain = org.taxi
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
icon.filename = %(source.dir)s/icon.png
version = 1.0
requirements = python3,kivy==2.3.0
orientation = portrait
fullscreen = 0
android.permissions = INTERNET
android.accept_sdk_license = True
android.archs = arm64-v8a
android.api = 30
android.minapi = 21
android.ndk = 25b
p4a.branch = master
log_level = 2
